/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SinAccesoRouteImport } from './routes/sin-acceso'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as ApiPublicHotmartWebhookRouteImport } from './routes/api/public/hotmart-webhook'
import { Route as ApiPublicCronRecordatoriosRouteImport } from './routes/api/public/cron-recordatorios'
import { Route as AuthenticatedAppSuscripcionRouteImport } from './routes/_authenticated/_app.suscripcion'
import { Route as AuthenticatedAppProgresoRouteImport } from './routes/_authenticated/_app.progreso'
import { Route as AuthenticatedAppPlatoRouteImport } from './routes/_authenticated/_app.plato'
import { Route as AuthenticatedAppPlanRouteImport } from './routes/_authenticated/_app.plan'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app.dashboard'
import { Route as AuthenticatedAppCuentaRouteImport } from './routes/_authenticated/_app.cuenta'
import { Route as AuthenticatedAppComprasRouteImport } from './routes/_authenticated/_app.compras'
import { Route as AuthenticatedAppCoachRouteImport } from './routes/_authenticated/_app.coach'
import { Route as AuthenticatedAppBibliotecaRouteImport } from './routes/_authenticated/_app.biblioteca'
import { Route as AuthenticatedAppAjustesRouteImport } from './routes/_authenticated/_app.ajustes'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SinAccesoRoute = SinAccesoRouteImport.update({
  id: '/sin-acceso',
  path: '/sin-acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHotmartWebhookRoute = ApiPublicHotmartWebhookRouteImport.update({
  id: '/api/public/hotmart-webhook',
  path: '/api/public/hotmart-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRecordatoriosRoute =
  ApiPublicCronRecordatoriosRouteImport.update({
    id: '/api/public/cron-recordatorios',
    path: '/api/public/cron-recordatorios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSuscripcionRoute =
  AuthenticatedAppSuscripcionRouteImport.update({
    id: '/suscripcion',
    path: '/suscripcion',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProgresoRoute =
  AuthenticatedAppProgresoRouteImport.update({
    id: '/progreso',
    path: '/progreso',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlatoRoute = AuthenticatedAppPlatoRouteImport.update({
  id: '/plato',
  path: '/plato',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPlanRoute = AuthenticatedAppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCuentaRoute = AuthenticatedAppCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppComprasRoute = AuthenticatedAppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCoachRoute = AuthenticatedAppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBibliotecaRoute =
  AuthenticatedAppBibliotecaRouteImport.update({
    id: '/biblioteca',
    path: '/biblioteca',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAjustesRoute = AuthenticatedAppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/signup': typeof SignupRoute
  '/sin-acceso': typeof SinAccesoRoute
  '/terminos': typeof TerminosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ajustes': typeof AuthenticatedAppAjustesRoute
  '/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/coach': typeof AuthenticatedAppCoachRoute
  '/compras': typeof AuthenticatedAppComprasRoute
  '/cuenta': typeof AuthenticatedAppCuentaRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/plan': typeof AuthenticatedAppPlanRoute
  '/plato': typeof AuthenticatedAppPlatoRoute
  '/progreso': typeof AuthenticatedAppProgresoRoute
  '/suscripcion': typeof AuthenticatedAppSuscripcionRoute
  '/api/public/cron-recordatorios': typeof ApiPublicCronRecordatoriosRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/signup': typeof SignupRoute
  '/sin-acceso': typeof SinAccesoRoute
  '/terminos': typeof TerminosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ajustes': typeof AuthenticatedAppAjustesRoute
  '/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/coach': typeof AuthenticatedAppCoachRoute
  '/compras': typeof AuthenticatedAppComprasRoute
  '/cuenta': typeof AuthenticatedAppCuentaRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/plan': typeof AuthenticatedAppPlanRoute
  '/plato': typeof AuthenticatedAppPlatoRoute
  '/progreso': typeof AuthenticatedAppProgresoRoute
  '/suscripcion': typeof AuthenticatedAppSuscripcionRoute
  '/api/public/cron-recordatorios': typeof ApiPublicCronRecordatoriosRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/signup': typeof SignupRoute
  '/sin-acceso': typeof SinAccesoRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_app/ajustes': typeof AuthenticatedAppAjustesRoute
  '/_authenticated/_app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/_authenticated/_app/coach': typeof AuthenticatedAppCoachRoute
  '/_authenticated/_app/compras': typeof AuthenticatedAppComprasRoute
  '/_authenticated/_app/cuenta': typeof AuthenticatedAppCuentaRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/plan': typeof AuthenticatedAppPlanRoute
  '/_authenticated/_app/plato': typeof AuthenticatedAppPlatoRoute
  '/_authenticated/_app/progreso': typeof AuthenticatedAppProgresoRoute
  '/_authenticated/_app/suscripcion': typeof AuthenticatedAppSuscripcionRoute
  '/api/public/cron-recordatorios': typeof ApiPublicCronRecordatoriosRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacidad'
    | '/signup'
    | '/sin-acceso'
    | '/terminos'
    | '/onboarding'
    | '/ajustes'
    | '/biblioteca'
    | '/coach'
    | '/compras'
    | '/cuenta'
    | '/dashboard'
    | '/plan'
    | '/plato'
    | '/progreso'
    | '/suscripcion'
    | '/api/public/cron-recordatorios'
    | '/api/public/hotmart-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidad'
    | '/signup'
    | '/sin-acceso'
    | '/terminos'
    | '/onboarding'
    | '/ajustes'
    | '/biblioteca'
    | '/coach'
    | '/compras'
    | '/cuenta'
    | '/dashboard'
    | '/plan'
    | '/plato'
    | '/progreso'
    | '/suscripcion'
    | '/api/public/cron-recordatorios'
    | '/api/public/hotmart-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacidad'
    | '/signup'
    | '/sin-acceso'
    | '/terminos'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/ajustes'
    | '/_authenticated/_app/biblioteca'
    | '/_authenticated/_app/coach'
    | '/_authenticated/_app/compras'
    | '/_authenticated/_app/cuenta'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/plan'
    | '/_authenticated/_app/plato'
    | '/_authenticated/_app/progreso'
    | '/_authenticated/_app/suscripcion'
    | '/api/public/cron-recordatorios'
    | '/api/public/hotmart-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SignupRoute: typeof SignupRoute
  SinAccesoRoute: typeof SinAccesoRoute
  TerminosRoute: typeof TerminosRoute
  ApiPublicCronRecordatoriosRoute: typeof ApiPublicCronRecordatoriosRoute
  ApiPublicHotmartWebhookRoute: typeof ApiPublicHotmartWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sin-acceso': {
      id: '/sin-acceso'
      path: '/sin-acceso'
      fullPath: '/sin-acceso'
      preLoaderRoute: typeof SinAccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hotmart-webhook': {
      id: '/api/public/hotmart-webhook'
      path: '/api/public/hotmart-webhook'
      fullPath: '/api/public/hotmart-webhook'
      preLoaderRoute: typeof ApiPublicHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-recordatorios': {
      id: '/api/public/cron-recordatorios'
      path: '/api/public/cron-recordatorios'
      fullPath: '/api/public/cron-recordatorios'
      preLoaderRoute: typeof ApiPublicCronRecordatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/suscripcion': {
      id: '/_authenticated/_app/suscripcion'
      path: '/suscripcion'
      fullPath: '/suscripcion'
      preLoaderRoute: typeof AuthenticatedAppSuscripcionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/progreso': {
      id: '/_authenticated/_app/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedAppProgresoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/plato': {
      id: '/_authenticated/_app/plato'
      path: '/plato'
      fullPath: '/plato'
      preLoaderRoute: typeof AuthenticatedAppPlatoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/plan': {
      id: '/_authenticated/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedAppPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/cuenta': {
      id: '/_authenticated/_app/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedAppCuentaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/compras': {
      id: '/_authenticated/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedAppComprasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/coach': {
      id: '/_authenticated/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedAppCoachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/biblioteca': {
      id: '/_authenticated/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedAppBibliotecaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/ajustes': {
      id: '/_authenticated/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAppAjustesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAjustesRoute: typeof AuthenticatedAppAjustesRoute
  AuthenticatedAppBibliotecaRoute: typeof AuthenticatedAppBibliotecaRoute
  AuthenticatedAppCoachRoute: typeof AuthenticatedAppCoachRoute
  AuthenticatedAppComprasRoute: typeof AuthenticatedAppComprasRoute
  AuthenticatedAppCuentaRoute: typeof AuthenticatedAppCuentaRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppPlanRoute: typeof AuthenticatedAppPlanRoute
  AuthenticatedAppPlatoRoute: typeof AuthenticatedAppPlatoRoute
  AuthenticatedAppProgresoRoute: typeof AuthenticatedAppProgresoRoute
  AuthenticatedAppSuscripcionRoute: typeof AuthenticatedAppSuscripcionRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAjustesRoute: AuthenticatedAppAjustesRoute,
  AuthenticatedAppBibliotecaRoute: AuthenticatedAppBibliotecaRoute,
  AuthenticatedAppCoachRoute: AuthenticatedAppCoachRoute,
  AuthenticatedAppComprasRoute: AuthenticatedAppComprasRoute,
  AuthenticatedAppCuentaRoute: AuthenticatedAppCuentaRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppPlanRoute: AuthenticatedAppPlanRoute,
  AuthenticatedAppPlatoRoute: AuthenticatedAppPlatoRoute,
  AuthenticatedAppProgresoRoute: AuthenticatedAppProgresoRoute,
  AuthenticatedAppSuscripcionRoute: AuthenticatedAppSuscripcionRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadRoute: PrivacidadRoute,
  SignupRoute: SignupRoute,
  SinAccesoRoute: SinAccesoRoute,
  TerminosRoute: TerminosRoute,
  ApiPublicCronRecordatoriosRoute: ApiPublicCronRecordatoriosRoute,
  ApiPublicHotmartWebhookRoute: ApiPublicHotmartWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
