/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppSuscripcionRouteImport } from './routes/_authenticated/_app.suscripcion'
import { Route as AuthenticatedAppProgresoRouteImport } from './routes/_authenticated/_app.progreso'
import { Route as AuthenticatedAppPlanRouteImport } from './routes/_authenticated/_app.plan'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app.dashboard'
import { Route as AuthenticatedAppCuentaRouteImport } from './routes/_authenticated/_app.cuenta'
import { Route as AuthenticatedAppComprasRouteImport } from './routes/_authenticated/_app.compras'
import { Route as AuthenticatedAppCoachRouteImport } from './routes/_authenticated/_app.coach'
import { Route as AuthenticatedAppAjustesRouteImport } from './routes/_authenticated/_app.ajustes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppSuscripcionRoute =
  AuthenticatedAppSuscripcionRouteImport.update({
    id: '/suscripcion',
    path: '/suscripcion',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProgresoRoute =
  AuthenticatedAppProgresoRouteImport.update({
    id: '/progreso',
    path: '/progreso',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlanRoute = AuthenticatedAppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCuentaRoute = AuthenticatedAppCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppComprasRoute = AuthenticatedAppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCoachRoute = AuthenticatedAppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAjustesRoute = AuthenticatedAppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ajustes': typeof AuthenticatedAppAjustesRoute
  '/coach': typeof AuthenticatedAppCoachRoute
  '/compras': typeof AuthenticatedAppComprasRoute
  '/cuenta': typeof AuthenticatedAppCuentaRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/plan': typeof AuthenticatedAppPlanRoute
  '/progreso': typeof AuthenticatedAppProgresoRoute
  '/suscripcion': typeof AuthenticatedAppSuscripcionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ajustes': typeof AuthenticatedAppAjustesRoute
  '/coach': typeof AuthenticatedAppCoachRoute
  '/compras': typeof AuthenticatedAppComprasRoute
  '/cuenta': typeof AuthenticatedAppCuentaRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/plan': typeof AuthenticatedAppPlanRoute
  '/progreso': typeof AuthenticatedAppProgresoRoute
  '/suscripcion': typeof AuthenticatedAppSuscripcionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_app/ajustes': typeof AuthenticatedAppAjustesRoute
  '/_authenticated/_app/coach': typeof AuthenticatedAppCoachRoute
  '/_authenticated/_app/compras': typeof AuthenticatedAppComprasRoute
  '/_authenticated/_app/cuenta': typeof AuthenticatedAppCuentaRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/plan': typeof AuthenticatedAppPlanRoute
  '/_authenticated/_app/progreso': typeof AuthenticatedAppProgresoRoute
  '/_authenticated/_app/suscripcion': typeof AuthenticatedAppSuscripcionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/ajustes'
    | '/coach'
    | '/compras'
    | '/cuenta'
    | '/dashboard'
    | '/plan'
    | '/progreso'
    | '/suscripcion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/ajustes'
    | '/coach'
    | '/compras'
    | '/cuenta'
    | '/dashboard'
    | '/plan'
    | '/progreso'
    | '/suscripcion'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/ajustes'
    | '/_authenticated/_app/coach'
    | '/_authenticated/_app/compras'
    | '/_authenticated/_app/cuenta'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/plan'
    | '/_authenticated/_app/progreso'
    | '/_authenticated/_app/suscripcion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/suscripcion': {
      id: '/_authenticated/_app/suscripcion'
      path: '/suscripcion'
      fullPath: '/suscripcion'
      preLoaderRoute: typeof AuthenticatedAppSuscripcionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/progreso': {
      id: '/_authenticated/_app/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedAppProgresoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/plan': {
      id: '/_authenticated/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedAppPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/cuenta': {
      id: '/_authenticated/_app/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedAppCuentaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/compras': {
      id: '/_authenticated/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedAppComprasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/coach': {
      id: '/_authenticated/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedAppCoachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/ajustes': {
      id: '/_authenticated/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAppAjustesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAjustesRoute: typeof AuthenticatedAppAjustesRoute
  AuthenticatedAppCoachRoute: typeof AuthenticatedAppCoachRoute
  AuthenticatedAppComprasRoute: typeof AuthenticatedAppComprasRoute
  AuthenticatedAppCuentaRoute: typeof AuthenticatedAppCuentaRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppPlanRoute: typeof AuthenticatedAppPlanRoute
  AuthenticatedAppProgresoRoute: typeof AuthenticatedAppProgresoRoute
  AuthenticatedAppSuscripcionRoute: typeof AuthenticatedAppSuscripcionRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAjustesRoute: AuthenticatedAppAjustesRoute,
  AuthenticatedAppCoachRoute: AuthenticatedAppCoachRoute,
  AuthenticatedAppComprasRoute: AuthenticatedAppComprasRoute,
  AuthenticatedAppCuentaRoute: AuthenticatedAppCuentaRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppPlanRoute: AuthenticatedAppPlanRoute,
  AuthenticatedAppProgresoRoute: AuthenticatedAppProgresoRoute,
  AuthenticatedAppSuscripcionRoute: AuthenticatedAppSuscripcionRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
